import Head from 'next/head'
import Graph from '../components/graph'
import Timer from '../components/timer'
import Music from '../components/music'
import Buttons from '../components/buttons'
import Todo from '../components/todo'
import Notes from '../components/notes'
import Lb from '../components/lb'
import Gsearrch from '../components/Gsearrch'
import Time from '../components/Time'

export default function Home() {
  return (
    <div className="relative h-screen w-screen overflow-hidden pt-1 p-4 flex flex-col" >
      <img src='/svg/bg.png' className='w-[100vw] top-[-10px] left-[-10px] z-[-10] absolute'/>
      <Head>
        <title>Focusi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid grid-cols-10  p-4 place-items-center gap-8'>
          <img className='col-span-3 h-12 w-full' src='/svg/logo.svg' />
          <Gsearrch/>
          <Time/>
      </div>
      <div className='h-full  w-full grid  grid-cols-10 gap-x-8  pt-0 p-4 '>
        <div className='w-full md:col-span-3  py-4 pb-3  flex flex-col gap-y-5 '>
          <Todo />
          <Graph />
        </div>
        <div className='w-full col-span-4  py-4  flex flex-col gap-y-3 justify-between items-center'>
          <Timer />
          <Buttons/>
          <Music/>
        </div>
        <div className='w-full col-span-3  py-4  flex flex-col gap-y-5'>
          <Notes/>
          <Lb/>
        </div>
      </div>
    </div>
  )
}
