import { useEffect } from 'react'
import Head from 'next/head'
import Graph from '../components/Graph'
import Timer from '../components/timer'
import Music from '../components/music'
import Buttons from '../components/buttons'
import Todo from '../components/todo'
import Notes from '../components/notes'
import Lb from '../components/lb'
import Gsearrch from '../components/Gsearrch'
import Time from '../components/Time'
import { useContext } from 'react'
import { AppContext } from '../AppContext'
import {useRouter} from 'next/router'

export default function Home() {
  const { state } = useContext(AppContext)
  const router=useRouter()
  useEffect(() => {
    if(typeof JSON.parse(localStorage.getItem("data")).jwt==="object"){
      router.push("/login")
    }
  }, [])
  
  return (
    <div className="relative h-screen w-screen overflow-y-scroll lg:overflow-hidden pt-1 p-4 flex flex-col" >
      <img src={state.pomodoroStatus?"/svg/bgp.png":'/svg/bg2.svg'} className='w-[100vw] top-[-200px] left-0 z-[-10] absolute'/>
      <Head>
        <title>Focusi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid grid-cols-10  p-4 place-items-center gap-8'>
          <img className='col-span-3 h-12 w-full' src='/svg/logo.svg' />
          <Gsearrch/>
          <Time/>
      </div>
      <div className='h-full  w-full grid  grid-cols-10 gap-x-8  pt-0 p-4 '>
        <div className='w-full col-span-10 lg:col-span-3  py-4 pb-3  flex flex-col lg:gap-y-5 '>
          <div className='w-full h-[45vh]'><Todo /></div>
          <div className='w-full h-[30vh]'><Graph /></div>
        </div>
        <div className=' w-full col-span-10 lg:col-span-4  py-4  flex flex-col lg:gap-y-3 justify-between items-center'>
          <Timer />
          <div className='w-full flex flex-col gap-y-3'>
          <Buttons/>
          <Music/>
          </div>
        </div>
        <div className='w-full col-span-10 lg:col-span-3  py-4  flex flex-col lg:gap-y-5'>
          <div className='w-full h-[30vh]'><Notes/></div>
          <div className='w-full h-[45vh]'><Lb/></div>
        </div>
      </div>
    </div>
  )
}
